### PR TITLE
Operation Based Swift 3 Rebuild

### PR DESCRIPTION
**Pull request by keefmoon**
Ground up rebuild ofJustPromise in Swift 3 using `Operation`s as the base.

A `Promise` is a `Operation` with the future result state on top. Generics used to provide a future result of the right type, this is NOT Objective-C compatible.

The current code has 2 objects `JEPromise` and `JEFuture` but `JEPromise` did very little. So now the main object is `Promise`. All existing features supported except `JEProgress`, as I'm unsure what purpose it serves.

Check the updated ReadMe for details

### CODE REVIEW

**Comment by albertodebortoli** [comment]
@keefmoon this is gold! Thanks for the effort.

Just a few minor things non-code related before merging, if you could change:

- typo: "Promise has a generic constraint that defineds [...]"
- type: "[...] might be have..."
- "JUST EAT iOS Team", the new marketing name is "Just Eat"
- pick the License file from [JustPeek](https://github.com/justeat/JustPeek/blob/master/LICENSE)
- add yourself as author in the Podspec + justeat.ios.team@gmail.com
- please let's keep the plural also for the swift version (JustPromises, not JustPromise)
- there's no schema for the swift tests target, please generate it and put them all as shared schemes
- the unit tests don't compile:
screen shot 2016-12-04 at 17 17 25
- not sure why, but the playground doesn't find the module even if I build it:
screen shot 2016-12-04 at 17 22 15

**Comment by keefmoon** [comment]
@albertodebortoli Cool. I'm on it.

**Comment by keefmoon** [comment]
@albertodebortoli Think I've fixed everything

**Comment by albertodebortoli** [comment]
😎 Merging! 💥

**Pull request merged**
